### ISSUE TITLE
Question titles not displaying correctly

### ISSUE THREAD

**Issue by KafkaNoNeko** [open-resources/physics_bank#67]
Some questions have the following error because the title was not stored in the dictionary (since the questions work fine on PL, a lot of this went unnoticed): 

![image](https://user-images.githubusercontent.com/45921274/194780325-5b90ea08-db9b-43e4-aa5b-b544491e6364.png)

**Comment by firasm** [comment]
Thanks for pointing this out - good catch.

@nich-rees can I ask you to do a single PR with the question titles for all the ones that are missing?

You can find them here: https://firas.moosvi.com/oer/physics_bank/files/home.html 

There will be some sleuthing required to actually track down the questions first, but the error messages should give you some hints about where to find it:

```
System Message: ERROR/3 ( /home/runner/work/physics_bank/physics_bank/content/public/004.Kinematics(1D)/Motion Diagrams/position_graph/position_graph.md , line 79)

Substitution error:UndefinedError: ‘dict object’ has no attribute ‘vars’
```

The issue is that the `title` is not stored in the `data` dictionary.

**Comment by firasm** [comment]
This is now solved.
